name: Releases
on:
  push:
    tags:
      - v*
jobs:
  build:
    name: Releases
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Get Tag Name
        id: get_tag_name
        run: echo ::set-output name=NAME::${GITHUB_REF/refs\/tags\/v/}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.get_tag_name.outputs.NAME }}
          draft: true
          prerelease: false
